/* GENERATED by scripts/build_grammar_data.cjs — do not edit by hand. */
(function (global) {
    'use strict';
    global.UzGrammarIndex = global.UzGrammarIndex || {};
    global.UzGrammarIndex["A1"] = [
    {
        "id": 1,
        "title": "Salomlashish va xayrlashish",
        "description": "Rus tilida salomlashish va xayrlashish",
        "objective": "После этого материала вы узнаете формы приветствия и прощания и научитесь выбирать между «вы» и «ты».",
        "chars": 930,
        "images": 0
    },
    {
        "id": 2,
        "title": "1 dan 100 gacha sonlar",
        "description": "Rus tilida sonlarni o'qish va yozish",
        "objective": "После этого материала вы научитесь читать и записывать числа от 1 до 100.",
        "chars": 624,
        "images": 1
    },
    {
        "id": 3,
        "title": "Oila a'zolari va qarindoshlar",
        "description": "Oila va qarindoshlar haqida so'zlashish",
        "objective": "После этого материала вы научитесь называть членов семьи и согласовывать притяжательные местоимения.",
        "chars": 541,
        "images": 1
    },
    {
        "id": 4,
        "title": "Vaqt va ob-havo",
        "description": "Ob-havo, fasllar va vaqt ifodalari",
        "objective": "После этого материала вы научитесь говорить о погоде, временах года и месяцах.",
        "chars": 634,
        "images": 1
    },
    {
        "id": 5,
        "title": "Kasblar va mashg'ulotlar",
        "description": "Kasblar va ish haqida gapirish",
        "objective": "После этого материала вы научитесь называть профессию и отличать её от глагола «работать».",
        "chars": 628,
        "images": 1
    },
    {
        "id": 6,
        "title": "Shaharning joylari",
        "description": "Shahar atrofi va yo'nalishlar",
        "objective": "После этого материала вы научитесь называть места в городе и спрашивать дорогу.",
        "chars": 420,
        "images": 1
    },
    {
        "id": 7,
        "title": "Ovqatlanish va restoran",
        "description": "Ovqat va ichimliklar haqida",
        "objective": "После этого материала вы научитесь заказывать еду и напитки и говорить о своих предпочтениях.",
        "chars": 496,
        "images": 1
    },
    {
        "id": 8,
        "title": "Kiyim-kechak va moda",
        "description": "Kiyimlar va o'lchamlar haqida",
        "objective": "После этого материала вы научитесь называть одежду, размеры и цвета.",
        "chars": 526,
        "images": 1
    },
    {
        "id": 9,
        "title": "Transport va sayohat",
        "description": "Transport vositalari va yo'nalishlar",
        "objective": "После этого материала вы научитесь говорить о транспорте и направлении поездки.",
        "chars": 909,
        "images": 1
    },
    {
        "id": 10,
        "title": "Sog'liq va dorixona",
        "description": "Sog'liq va tibbiy yordam haqida",
        "objective": "После этого материала вы научитесь называть симптомы и объясняться в аптеке.",
        "chars": 942,
        "images": 1
    },
    {
        "id": 11,
        "title": "Xobbiy va bo'sh vaqt",
        "description": "Xobbi va dam olish haqida",
        "objective": "После этого материала вы научитесь говорить об увлечениях с глаголами «нравиться», «заниматься», «увлекаться», «интересоваться».",
        "chars": 2024,
        "images": 0
    },
    {
        "id": 12,
        "title": "Qoidalar va maslahatlar",
        "description": "Maslahat berish va qoidalar",
        "objective": "После этого материала вы научитесь выражать разрешение, запрет, необходимость и совет.",
        "chars": 1932,
        "images": 0
    }
];
})(typeof window !== 'undefined' ? window : this);
