/* GENERATED by scripts/build_grammar_data.cjs — do not edit by hand. */
(function (global) {
    'use strict';
    global.UzGrammarIndex = global.UzGrammarIndex || {};
    global.UzGrammarIndex["A2"] = [
    {
        "id": 1,
        "title": "«У меня есть» va kundalik hayotim",
        "description": "Grammatika: «быть» fe'li. o'zingni tanishtirish",
        "objective": "После этого материала вы научитесь пользоваться глаголом «быть» и конструкцией «у меня есть».",
        "chars": 4257,
        "images": 0
    },
    {
        "id": 2,
        "title": "Oila va munosabatlar",
        "description": "Grammatika: O'tgan zamon, egalik olmoshlari",
        "objective": "После этого материала вы научитесь говорить о прошлом и пользоваться притяжательными местоимениями.",
        "chars": 3863,
        "images": 0
    },
    {
        "id": 3,
        "title": "Uy va yashash joyi",
        "description": "Grammatika: Prepozitsion kelishik, joy ma'noli so'zlar",
        "objective": "После этого материала вы научитесь различать место и направление с предлогами и падежами.",
        "chars": 3613,
        "images": 0
    },
    {
        "id": 4,
        "title": "Kunlar, oylar va fasllar",
        "description": "Vaqt va fasllar haqida so'zlashish",
        "objective": "После этого материала вы научитесь называть дни, месяцы, времена года и говорить о времени.",
        "chars": 4125,
        "images": 0
    },
    {
        "id": 5,
        "title": "Kasblar va mashg'ulotlar",
        "description": "Kasblar va ish haqida gapirish",
        "objective": "После этого материала вы научитесь рассказывать о профессии и месте работы.",
        "chars": 4046,
        "images": 0
    },
    {
        "id": 6,
        "title": "Shaharning joylari",
        "description": "Shahar atrofi va yo'nalishlar",
        "objective": "После этого материала вы научитесь различать «в» и «на» для мест и направлений в городе.",
        "chars": 3737,
        "images": 0
    },
    {
        "id": 7,
        "title": "Ovqatlanish va restoran",
        "description": "Ovqat va ichimliklar haqida",
        "objective": "После этого материала вы научитесь заказывать в ресторане и выражать желание.",
        "chars": 2939,
        "images": 0
    },
    {
        "id": 8,
        "title": "Kiyim-kechak va moda",
        "description": "Kiyimlar va o'lchamlar haqida",
        "objective": "После этого материала вы научитесь описывать одежду вопросами «какой? какая? какое? какие?».",
        "chars": 4459,
        "images": 0
    },
    {
        "id": 9,
        "title": "Transport va sayohat",
        "description": "Transport vositalari va yo'nalishlar",
        "objective": "После этого материала вы научитесь различать «ехать/ездить» и «идти/ходить» и называть транспорт.",
        "chars": 4240,
        "images": 0
    },
    {
        "id": 10,
        "title": "Sog'liq va dorixona",
        "description": "Sog'liq va tibbiy yordam haqida",
        "objective": "После этого материала вы научитесь описывать симптомы и объяснять, что вам нужно.",
        "chars": 3414,
        "images": 0
    },
    {
        "id": 11,
        "title": "Хобби, свободное время и отдых",
        "description": "Xobbi, bo'sh vaqt va dam olish haqida",
        "objective": "После этого материала вы научитесь говорить о хобби и свободном времени.",
        "chars": 4058,
        "images": 0
    },
    {
        "id": 12,
        "title": "Qoidalar va maslahatlar",
        "description": "Maslahat berish va qoidalar",
        "objective": "После этого материала вы научитесь выражать правила, разрешение и запрет.",
        "chars": 4644,
        "images": 0
    },
    {
        "id": 13,
        "title": "O‘tmish va kelajak vaqt shakllari. Istaklar",
        "description": "Vaqt shakllari va istaklar",
        "objective": "После этого материала вы научитесь говорить о прошлом и будущем и выражать желания.",
        "chars": 4862,
        "images": 0
    },
    {
        "id": 14,
        "title": "Taqqoslash va tanlov",
        "description": "Qiyosiy daraja, eng yuqori daraja va tanlov",
        "objective": "После этого материала вы научитесь сравнивать предметы и делать выбор.",
        "chars": 7573,
        "images": 0
    },
    {
        "id": 15,
        "title": "Muloqot va munosabatlar",
        "description": "Muloqot, fikr bildirish va munosabatlar",
        "objective": "После этого материала вы научитесь говорить о общении и отношениях с предлогом «с» и дательным падежом.",
        "chars": 8046,
        "images": 0
    },
    {
        "id": 16,
        "title": "Madaniyat va an'analar",
        "description": "Madaniyat, an'analar va bayramlar",
        "objective": "После этого материала вы научитесь говорить о культуре и традициях и пользоваться степенями сравнения.",
        "chars": 6643,
        "images": 0
    }
];
})(typeof window !== 'undefined' ? window : this);
