/* GENERATED by scripts/build_grammar_data.cjs — do not edit by hand. */
(function (global) {
    'use strict';
    global.UzGrammarIndex = global.UzGrammarIndex || {};
    global.UzGrammarIndex["B1"] = [
    {
        "id": 1,
        "title": "Shaxs va hayot tajribasi",
        "description": "Grammatika: СВ va НСВ (mukammal va nomukammal fe'l turi). Muloqot: o'tmishdagi voqealar",
        "objective": "После этого материала вы научитесь различать совершенный и несовершенный вид глагола.",
        "chars": 1510,
        "images": 0
    },
    {
        "id": 2,
        "title": "Bolalik va xotiralar",
        "description": "Grammatika: ходить/ездить, раньше/когда/пока. Mavzu: bolalik va o'tmish xotiralari",
        "objective": "После этого материала вы научитесь рассказывать о детстве с «ходить/ездить» и словами «раньше», «когда», «пока».",
        "chars": 1669,
        "images": 0
    },
    {
        "id": 3,
        "title": "Ta'lim va shaxsiy rivojlanish",
        "description": "Grammatika: что/чтобы, СВ/НСВ, harakat maqsadi va natijasi. Mavzu: ta'lim va rivojlanish",
        "objective": "После этого материала вы научитесь различать «что» и «чтобы».",
        "chars": 1612,
        "images": 0
    },
    {
        "id": 4,
        "title": "Ish va karyera",
        "description": "Ish, martaba va motivatsiya haqida suhbat",
        "objective": "После этого материала вы научитесь объяснять причину, цель и результат.",
        "chars": 1531,
        "images": 0
    },
    {
        "id": 5,
        "title": "Muammolar va hissiyotlar",
        "description": "Hissiyotlar, muammolar va kundalik stress haqida suhbat",
        "objective": "После этого материала вы научитесь пользоваться возвратными глаголами на -ся/-сь.",
        "chars": 1313,
        "images": 0
    },
    {
        "id": 6,
        "title": "Sog'lom turmush tarzi",
        "description": "Sog'liq, foydali odatlar va sog'lom hayot haqida suhbat",
        "objective": "После этого материала вы научитесь выражать обязанность и рекомендацию.",
        "chars": 1540,
        "images": 0
    },
    {
        "id": 7,
        "title": "Sayohat va harakat",
        "description": "Sayohat, transport va harakat fe'llari haqida suhbat",
        "objective": "После этого материала вы научитесь пользоваться глаголами движения с приставками.",
        "chars": 1593,
        "images": 0
    },
    {
        "id": 8,
        "title": "Oila va an'analar",
        "description": "Oila, urf-odatlar, bayramlar va qiyosiy daraja haqida suhbat",
        "objective": "После этого материала вы научитесь строить сравнительную и превосходную степень прилагательных.",
        "chars": 1435,
        "images": 0
    },
    {
        "id": 9,
        "title": "Internet va ijtimoiy tarmoqlar",
        "description": "Internet, telefon, ijtimoiy tarmoqlar va zamonaviy aloqa vositalari haqida suhbat",
        "objective": "После этого материала вы научитесь выбирать «в» или «по» с медиа и интернетом.",
        "chars": 1544,
        "images": 0
    },
    {
        "id": 10,
        "title": "His-tuyg'ular va munosabatlar",
        "description": "His-tuyg'ular, emotsiyalar va возвратные глаголы mavzusi",
        "objective": "После этого материала вы научитесь говорить о чувствах и отношениях с возвратными глаголами.",
        "chars": 1799,
        "images": 0
    },
    {
        "id": 11,
        "title": "Xarakter va shaxs tavsifi",
        "description": "Grammatika: sifat + ravishlar. Muloqot: odamlarni tavsiflash, narxlarni solishtirish",
        "objective": "После этого материала вы научитесь описывать характер человека прилагательными и наречиями.",
        "chars": 2042,
        "images": 0
    },
    {
        "id": 12,
        "title": "Texnologiya va kundalik hayot",
        "description": "Grammatika: пассив konstruktsiyalar (oddiy). Muloqot: texnologiyaning foydasi va zarari",
        "objective": "После этого материала вы научитесь понимать и строить страдательный залог.",
        "chars": 1687,
        "images": 0
    },
    {
        "id": 13,
        "title": "Bahs va fikr bildirish",
        "description": "Grammatika: я думаю, я считаю, по-моему. Muloqot: fikrni himoya qilish",
        "objective": "После этого материала вы научитесь выражать и защищать своё мнение.",
        "chars": 1538,
        "images": 0
    },
    {
        "id": 14,
        "title": "Kelajak rejalari va orzular",
        "description": "Grammatika: murakkab kelasi zamon tuzilmalari. Muloqot: rejalar, orzular haqida gapirish",
        "objective": "После этого материала вы научитесь говорить о планах и мечтах в будущем времени.",
        "chars": 1557,
        "images": 0
    },
    {
        "id": 15,
        "title": "Muammoli vaziyatlar",
        "description": "Grammatika: buyruq shaklining murakkab turlari. Muloqot: shikoyat, norozilik bildirish",
        "objective": "После этого материала вы научитесь пользоваться повелительным наклонением и выражать недовольство.",
        "chars": 1513,
        "images": 0
    },
    {
        "id": 16,
        "title": "Jamiyat va shaxs",
        "description": "Grammatika: umumlashtiruvchi gaplar. Muloqot: ijtimoiy mavzularda suhbat",
        "objective": "После этого материала вы научитесь строить обобщающие высказывания о обществе.",
        "chars": 1674,
        "images": 0
    },
    {
        "id": 17,
        "title": "Pul, xarajatlar va rejalashtirish",
        "description": "Grammatika: родительный падеж (много денег, нет времени), miqdor so'zlari. Muloqot: xarajatlar, tejash, reja tuzish",
        "objective": "После этого материала вы научитесь пользоваться родительным падежом для отсутствия и количества.",
        "chars": 1615,
        "images": 0
    },
    {
        "id": 18,
        "title": "Xizmat ko'rsatish va rasmiy muomala",
        "description": "Grammatika: вежливые формы, дательный падеж (вам, мне). Muloqot: bank, pochta, ofis, rasmiy murojaat",
        "objective": "После этого материала вы научитесь пользоваться дательным падежом и вежливыми формами обращения.",
        "chars": 1816,
        "images": 0
    },
    {
        "id": 19,
        "title": "Qoidalar, qonun va majburiyatlar",
        "description": "Grammatika: нельзя / можно / разрешено / запрещено. Muloqot: qoidalarni tushuntirish, ogohlantirish",
        "objective": "После этого материала вы научитесь выражать правила, разрешение и запрет, в том числе официальные.",
        "chars": 1611,
        "images": 0
    },
    {
        "id": 20,
        "title": "Favqulodda holatlar va muammoli vaziyatlar",
        "description": "Grammatika: прошедшее время + если, sabab–natija. Muloqot: yordam so'rash, vaziyatni tushuntirish",
        "objective": "После этого материала вы научитесь рассказывать о происшествиях с прошедшим временем и условием «если».",
        "chars": 1541,
        "images": 0
    }
];
})(typeof window !== 'undefined' ? window : this);
