/* GENERATED by scripts/build_grammar_data.cjs — do not edit by hand. */
(function (global) {
    'use strict';
    global.UzGrammarIndex = global.UzGrammarIndex || {};
    global.UzGrammarIndex["B2"] = [
    {
        "id": 1,
        "title": "Сложноподчинённые предложения",
        "description": "Grammatika: Ergash gapli qo‘shma gaplar: что, чтобы, если, когда, потому что, хотя. Muloqot: Shaxsiy qarashlar, hayotiy pozitsiya, fikrni asoslash",
        "objective": "После этого материала вы научитесь строить сложноподчинённые предложения.",
        "chars": 4136,
        "images": 0
    },
    {
        "id": 2,
        "title": "Причастие",
        "description": "Grammatika: Sifatdosh: hozirgi va o‘tgan zamon, aniq va majhul nisbat. Muloqot: Tavsiflash, matnni siqish, rasmiy va ilmiy uslub",
        "objective": "После этого материала вы научитесь образовывать и употреблять причастия.",
        "chars": 4057,
        "images": 0
    },
    {
        "id": 3,
        "title": "Деепричастие",
        "description": "Grammatika: Ravishdosh: tugallanmagan va tugallangan ko‘rinishlar. Muloqot: Bir vaqtda sodir bo‘lgan harakatlar, sabab va shartni ifodalash",
        "objective": "После этого материала вы научитесь образовывать и употреблять деепричастия.",
        "chars": 2965,
        "images": 0
    },
    {
        "id": 4,
        "title": "Прямая и косвенная речь",
        "description": "Grammatika: To‘g‘ri va o‘zlashtirma gap, olmosh va zamon almashuvi. Muloqot: Boshqalarning so‘zini yetkazish, suhbatni qayta hikoya qilish",
        "objective": "После этого материала вы научитесь строить условные предложения.",
        "chars": 3288,
        "images": 0
    },
    {
        "id": 5,
        "title": "Условные предложения",
        "description": "Grammatika: Shart gaplar: real, noreal va o‘tmishga oid shart. Muloqot: Taxmin, ehtimol, rejalar va afsuslanishni ifodalash",
        "objective": "После этого материала вы научитесь пользоваться страдательным залогом.",
        "chars": 3692,
        "images": 0
    },
    {
        "id": 6,
        "title": "Сравнительные конструкции",
        "description": "Grammatika: Qiyosiy va orttirma daraja, qiyoslash vositalari. Muloqot: Taqqoslash, tanlovni asoslash, afzallik berish",
        "objective": "После этого материала вы научитесь передавать чужую речь.",
        "chars": 6013,
        "images": 0
    },
    {
        "id": 7,
        "title": "Вид глагола",
        "description": "Grammatika: Fe‘l ko‘rinishi: tugallanmagan va tugallangan nisbat. Muloqot: Jarayon va natijani farqlash, hikoya qilish",
        "objective": "После этого материала вы научитесь пользоваться сложными предлогами и связками.",
        "chars": 10776,
        "images": 0
    },
    {
        "id": 8,
        "title": "Глаголы движения с приставками",
        "description": "Grammatika: Harakat fe‘llari va old qo‘shimchalar ma‘nosi. Muloqot: Yo‘nalish, marshrut, sayohat va ko‘chishni tasvirlash",
        "objective": "После этого материала вы научитесь строить уступительные конструкции.",
        "chars": 7849,
        "images": 0
    },
    {
        "id": 9,
        "title": "Модальные конструкции",
        "description": "Grammatika: Modallik: imkoniyat, zarurat, ruxsat va taqiq. Muloqot: Maslahat berish, talab qo‘yish, qoidalarni tushuntirish",
        "objective": "После этого материала вы научитесь выражать причину и следствие в развёрнутой речи.",
        "chars": 6672,
        "images": 0
    },
    {
        "id": 10,
        "title": "Безличные предложения",
        "description": "Grammatika: Shaxssiz gaplar va ularning turlari. Muloqot: Holat, kayfiyat, tabiat hodisalari va his-tuyg‘ular",
        "objective": "После этого материала вы научитесь пользоваться сложными формами времени и вида.",
        "chars": 8812,
        "images": 0
    },
    {
        "id": 11,
        "title": "Отглагольные существительные",
        "description": "Grammatika: Fe‘ldan yasalgan otlar va ularning yasalishi. Muloqot: Rasmiy hujjat tili, ilmiy matn, hisobot va tahlil",
        "objective": "После этого материала вы научитесь выражать оценку и модальность.",
        "chars": 5684,
        "images": 0
    },
    {
        "id": 12,
        "title": "Пассивные конструкции",
        "description": "Grammatika: Majhul nisbat: qisqa sifatdosh va -ся shakllari. Muloqot: Xolis bayon, rasmiy uslub, yangiliklar va e‘lonlar",
        "objective": "После этого материала вы научитесь строить развёрнутое описание и определение.",
        "chars": 5957,
        "images": 0
    },
    {
        "id": 13,
        "title": "Предлоги и управление",
        "description": "Grammatika: Ko‘makchilar va fe‘l boshqaruvi, kelishik tanlovi. Muloqot: Aniq va xatosiz ifoda, yozma nutq madaniyati",
        "objective": "После этого материала вы научитесь вести аргументированную дискуссию.",
        "chars": 8762,
        "images": 0
    },
    {
        "id": 14,
        "title": "Средства аргументации",
        "description": "Grammatika: Dalil keltirish vositalari va mantiqiy bog‘lovchilar. Muloqot: Bahs, munozara, insho va nutqni tuzish",
        "objective": "После этого материала вы научитесь пользоваться конструкциями цели и намерения.",
        "chars": 8172,
        "images": 0
    },
    {
        "id": 15,
        "title": "Стилистика речи",
        "description": "Grammatika: Nutq uslublari: so‘zlashuv, rasmiy, ilmiy, publitsistik. Muloqot: Vaziyatga qarab uslubni almashtirish, xat va murojaat",
        "objective": "После этого материала вы научитесь строить официальное и деловое высказывание.",
        "chars": 6774,
        "images": 0
    },
    {
        "id": 16,
        "title": "Повторение сложных конструкций B2",
        "description": "Grammatika: B2 darajasidagi barcha murakkab konstruksiyalarni takrorlash. Muloqot: Kompleks amaliyot, imtihonga tayyorgarlik, erkin nutq",
        "objective": "После этого материала вы научитесь связывать высказывание в целостный текст.",
        "chars": 7975,
        "images": 0
    }
];
})(typeof window !== 'undefined' ? window : this);
