#!/usr/bin/env node
/**
 * build_server_canon.cjs — regenerate api/_lib/course-canon.js from the REAL
 * course and exam content.
 *
 * The server must validate topics and score final exams without reading the
 * course HTML at runtime: a serverless bundle is not guaranteed to contain
 * those files. So the canonical data is extracted here, at authoring time, and
 * checked in as a plain module — which IS always bundled.
 *
 * Two copies of an answer key can drift apart silently, so they are not allowed
 * to: verify_progress_security.cjs re-extracts from the HTML on every run and
 * fails if this file no longer matches. Run this script after editing an exam.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const ROOT = path.join(__dirname, '..');

function literal(src, name) {
    const i = src.search(new RegExp('(?:const|let|var)\\s+' + name + '\\s*=\\s*[\\[{]'));
    if (i < 0) throw new Error('missing ' + name);
    let j = i;
    while (src[j] !== '[' && src[j] !== '{') j++;
    const open = src[j], close = open === '[' ? ']' : '}';
    let d = 0;
    for (let k = j; k < src.length; k++) {
        if (src[k] === open) d++;
        else if (src[k] === close) {
            d--;
            if (d === 0) return vm.runInNewContext('(' + src.slice(j, k + 1) + ')',
                { generateLockedTopics: () => [], icons: {}, lockedTopicNames: [] });
        }
    }
    throw new Error('unbalanced ' + name);
}

/* -------------------------------------- exams (A1, A2, B1 and B2) */
const EXAM_PAGES = {
    A1: 'paid-courses/a1-final-exam.html',
    A2: 'paid-courses/a2-final-exam.html',
    B1: 'paid-courses/b1-final-exam.html',
    B2: 'paid-courses/b2-final-exam.html'
};
const exams = {};
Object.entries(EXAM_PAGES).forEach(([course, rel]) => {
    const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    const data = literal(src, 'FINAL_EXAM_DATA');

    /* The punctuation class differs per exam (B1 also strips em/en dashes), so
       it is captured from the page rather than assumed. */
    const norm = src.match(/function normalizeExamText[\s\S]*?\n        \}/)[0];
    const punct = norm.match(/\.replace\(\/\[([^\]]*)\]\/g, ' '\)/)[1];
    const passed = src.match(/var (?:passed|previewPassed) = (?:finalScore|pct|previewPct) >= (\d+);/)[1];

    /* Only what grading needs — prompts and options are kept for the parity
       fingerprint, nothing else. */
    exams[course] = {
        punctuation: punct,
        passMark: Number(passed),
        groups: data.map((g) => ({
            title: g.title || g.section || '',
            type: g.type || 'mixed',
            items: (g.items || []).map((it) => ({
                q: it.q == null ? '' : String(it.q),
                opts: Array.isArray(it.opts) ? it.opts.slice() : null,
                answer: it.answer
            }))
        }))
    };
});

/* ------------------------------------------------------- topic manifests */
/* COURSE_TOTAL_TOPICS in my.cabinet/cabinet.js is the platform's single
   declaration of how many topics a course has — the dashboard progress bars
   already derive from it. B2 builds its topic list at runtime, so counting the
   ids in a page would under-report it; the declaration does not. The pages are
   still read below and their ids must be a SUBSET, which catches a course that
   grows past its declared size. */
const cabinet = fs.readFileSync(path.join(ROOT, 'my.cabinet/cabinet.js'), 'utf8');
const totals = vm.runInNewContext('(' +
    cabinet.slice(cabinet.indexOf('Object.freeze({', cabinet.indexOf('COURSE_TOTAL_TOPICS')) + 14,
        cabinet.indexOf('});', cabinet.indexOf('COURSE_TOTAL_TOPICS')) + 1) + ')', {});

const COURSE_PAGES = {
    A1: 'paid-courses/a1-course.html',
    A2: 'paid-courses/a2-course.html',
    B1: 'paid-courses/b1-course.html',
    B2: 'paid-courses/b2-course.html'
};
const courses = {};
Object.entries(COURSE_PAGES).forEach(([code, rel]) => {
    const total = Number(totals[code]);
    if (!Number.isInteger(total) || total <= 0) throw new Error('no declared total for ' + code);
    const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    let pageIds = [];
    try {
        pageIds = (literal(src, 'courseData').topics || []).map((t) => Number(t.id))
            .filter((n) => Number.isInteger(n) && n > 0);
    } catch (e) { pageIds = []; }
    const stray = pageIds.filter((n) => n > total);
    if (stray.length) throw new Error(code + ' has topics beyond its declared total: ' + stray.join(','));
    courses[code] = { totalTopics: total, topicIds: Array.from({ length: total }, (_, i) => i + 1) };
});

const out = `/**
 * course-canon.js — GENERATED by scripts/build_server_canon.cjs. Do not edit.
 *
 * The server's own copy of what a course contains and what a final exam
 * answers to. It exists because a serverless function cannot rely on the
 * course HTML being in its bundle, and because the client must never be the
 * authority on either.
 *
 * verify_progress_security.cjs re-extracts both from the real pages and fails
 * on any drift, so this file cannot quietly fall behind the content.
 */
export const COURSE_CANON = ${JSON.stringify(courses, null, 4)};

export const EXAM_CANON = ${JSON.stringify(exams, null, 4)};

export const COURSE_CODES = Object.freeze(Object.keys(COURSE_CANON));
export const EXAM_COURSES = Object.freeze(Object.keys(EXAM_CANON));
`;
fs.writeFileSync(path.join(ROOT, 'api/_lib/course-canon.js'), out);

Object.entries(courses).forEach(([c, v]) =>
    console.log(`  ${c}: ${v.totalTopics} тем (1..${v.totalTopics})`));
Object.entries(exams).forEach(([c, v]) =>
    console.log(`  ${c} экзамен: ${v.groups.length} групп, ` +
        `${v.groups.reduce((s, g) => s + g.items.length, 0)} позиций, порог ${v.passMark}`));
console.log('  → api/_lib/course-canon.js');
